// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: podr2-api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Podr2Api_RequestGenTag_FullMethodName = "/podr2.Podr2Api/request_gen_tag"
	Podr2Api_Echo_FullMethodName          = "/podr2.Podr2Api/Echo"
)

// Podr2ApiClient is the client API for Podr2Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Podr2ApiClient interface {
	RequestGenTag(ctx context.Context, opts ...grpc.CallOption) (Podr2Api_RequestGenTagClient, error)
	// A echo rpc to measure network RTT.
	Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoMessage, error)
}

type podr2ApiClient struct {
	cc grpc.ClientConnInterface
}

func NewPodr2ApiClient(cc grpc.ClientConnInterface) Podr2ApiClient {
	return &podr2ApiClient{cc}
}

func (c *podr2ApiClient) RequestGenTag(ctx context.Context, opts ...grpc.CallOption) (Podr2Api_RequestGenTagClient, error) {
	stream, err := c.cc.NewStream(ctx, &Podr2Api_ServiceDesc.Streams[0], Podr2Api_RequestGenTag_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &podr2ApiRequestGenTagClient{stream}
	return x, nil
}

type Podr2Api_RequestGenTagClient interface {
	Send(*RequestGenTag) error
	Recv() (*ResponseGenTag, error)
	grpc.ClientStream
}

type podr2ApiRequestGenTagClient struct {
	grpc.ClientStream
}

func (x *podr2ApiRequestGenTagClient) Send(m *RequestGenTag) error {
	return x.ClientStream.SendMsg(m)
}

func (x *podr2ApiRequestGenTagClient) Recv() (*ResponseGenTag, error) {
	m := new(ResponseGenTag)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *podr2ApiClient) Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoMessage, error) {
	out := new(EchoMessage)
	err := c.cc.Invoke(ctx, Podr2Api_Echo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Podr2ApiServer is the server API for Podr2Api service.
// All implementations must embed UnimplementedPodr2ApiServer
// for forward compatibility
type Podr2ApiServer interface {
	RequestGenTag(Podr2Api_RequestGenTagServer) error
	// A echo rpc to measure network RTT.
	Echo(context.Context, *EchoMessage) (*EchoMessage, error)
	mustEmbedUnimplementedPodr2ApiServer()
}

// UnimplementedPodr2ApiServer must be embedded to have forward compatible implementations.
type UnimplementedPodr2ApiServer struct {
}

func (UnimplementedPodr2ApiServer) RequestGenTag(Podr2Api_RequestGenTagServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestGenTag not implemented")
}
func (UnimplementedPodr2ApiServer) Echo(context.Context, *EchoMessage) (*EchoMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedPodr2ApiServer) mustEmbedUnimplementedPodr2ApiServer() {}

// UnsafePodr2ApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Podr2ApiServer will
// result in compilation errors.
type UnsafePodr2ApiServer interface {
	mustEmbedUnimplementedPodr2ApiServer()
}

func RegisterPodr2ApiServer(s grpc.ServiceRegistrar, srv Podr2ApiServer) {
	s.RegisterService(&Podr2Api_ServiceDesc, srv)
}

func _Podr2Api_RequestGenTag_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Podr2ApiServer).RequestGenTag(&podr2ApiRequestGenTagServer{stream})
}

type Podr2Api_RequestGenTagServer interface {
	Send(*ResponseGenTag) error
	Recv() (*RequestGenTag, error)
	grpc.ServerStream
}

type podr2ApiRequestGenTagServer struct {
	grpc.ServerStream
}

func (x *podr2ApiRequestGenTagServer) Send(m *ResponseGenTag) error {
	return x.ServerStream.SendMsg(m)
}

func (x *podr2ApiRequestGenTagServer) Recv() (*RequestGenTag, error) {
	m := new(RequestGenTag)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Podr2Api_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Podr2ApiServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Podr2Api_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Podr2ApiServer).Echo(ctx, req.(*EchoMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Podr2Api_ServiceDesc is the grpc.ServiceDesc for Podr2Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Podr2Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "podr2.Podr2Api",
	HandlerType: (*Podr2ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Podr2Api_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "request_gen_tag",
			Handler:       _Podr2Api_RequestGenTag_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "podr2-api.proto",
}

const (
	Podr2VerifierApi_RequestBatchVerify_FullMethodName = "/podr2.Podr2VerifierApi/request_batch_verify"
)

// Podr2VerifierApiClient is the client API for Podr2VerifierApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Podr2VerifierApiClient interface {
	RequestBatchVerify(ctx context.Context, in *RequestBatchVerify, opts ...grpc.CallOption) (*ResponseBatchVerify, error)
}

type podr2VerifierApiClient struct {
	cc grpc.ClientConnInterface
}

func NewPodr2VerifierApiClient(cc grpc.ClientConnInterface) Podr2VerifierApiClient {
	return &podr2VerifierApiClient{cc}
}

func (c *podr2VerifierApiClient) RequestBatchVerify(ctx context.Context, in *RequestBatchVerify, opts ...grpc.CallOption) (*ResponseBatchVerify, error) {
	out := new(ResponseBatchVerify)
	err := c.cc.Invoke(ctx, Podr2VerifierApi_RequestBatchVerify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Podr2VerifierApiServer is the server API for Podr2VerifierApi service.
// All implementations must embed UnimplementedPodr2VerifierApiServer
// for forward compatibility
type Podr2VerifierApiServer interface {
	RequestBatchVerify(context.Context, *RequestBatchVerify) (*ResponseBatchVerify, error)
	mustEmbedUnimplementedPodr2VerifierApiServer()
}

// UnimplementedPodr2VerifierApiServer must be embedded to have forward compatible implementations.
type UnimplementedPodr2VerifierApiServer struct {
}

func (UnimplementedPodr2VerifierApiServer) RequestBatchVerify(context.Context, *RequestBatchVerify) (*ResponseBatchVerify, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestBatchVerify not implemented")
}
func (UnimplementedPodr2VerifierApiServer) mustEmbedUnimplementedPodr2VerifierApiServer() {}

// UnsafePodr2VerifierApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Podr2VerifierApiServer will
// result in compilation errors.
type UnsafePodr2VerifierApiServer interface {
	mustEmbedUnimplementedPodr2VerifierApiServer()
}

func RegisterPodr2VerifierApiServer(s grpc.ServiceRegistrar, srv Podr2VerifierApiServer) {
	s.RegisterService(&Podr2VerifierApi_ServiceDesc, srv)
}

func _Podr2VerifierApi_RequestBatchVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBatchVerify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Podr2VerifierApiServer).RequestBatchVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Podr2VerifierApi_RequestBatchVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Podr2VerifierApiServer).RequestBatchVerify(ctx, req.(*RequestBatchVerify))
	}
	return interceptor(ctx, in, info, handler)
}

// Podr2VerifierApi_ServiceDesc is the grpc.ServiceDesc for Podr2VerifierApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Podr2VerifierApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "podr2.Podr2VerifierApi",
	HandlerType: (*Podr2VerifierApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "request_batch_verify",
			Handler:    _Podr2VerifierApi_RequestBatchVerify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "podr2-api.proto",
}
