// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0-devel
// 	protoc        v5.26.1
// source: podr2-api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_Success           StatusCode = 0
	StatusCode_Processing        StatusCode = 1
	StatusCode_InvalidParameters StatusCode = 10001
	StatusCode_InvalidPath       StatusCode = 10002
	StatusCode_InternalError     StatusCode = 10003
	StatusCode_OutOfMemory       StatusCode = 10004
	StatusCode_AlgorithmError    StatusCode = 10005
	StatusCode_UnknownError      StatusCode = 10006
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:     "Success",
		1:     "Processing",
		10001: "InvalidParameters",
		10002: "InvalidPath",
		10003: "InternalError",
		10004: "OutOfMemory",
		10005: "AlgorithmError",
		10006: "UnknownError",
	}
	StatusCode_value = map[string]int32{
		"Success":           0,
		"Processing":        1,
		"InvalidParameters": 10001,
		"InvalidPath":       10002,
		"InternalError":     10003,
		"OutOfMemory":       10004,
		"AlgorithmError":    10005,
		"UnknownError":      10006,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_podr2_api_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_podr2_api_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{0}
}

type EchoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EchoMsg []byte `protobuf:"bytes,1,opt,name=echo_msg,json=echoMsg,proto3" json:"echo_msg,omitempty"`
}

func (x *EchoMessage) Reset() {
	*x = EchoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podr2_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoMessage) ProtoMessage() {}

func (x *EchoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_podr2_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoMessage.ProtoReflect.Descriptor instead.
func (*EchoMessage) Descriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{0}
}

func (x *EchoMessage) GetEchoMsg() []byte {
	if x != nil {
		return x.EchoMsg
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	T       *Tag_T `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	PhiHash string `protobuf:"bytes,2,opt,name=phi_hash,json=phiHash,proto3" json:"phi_hash,omitempty"`
	Attest  string `protobuf:"bytes,3,opt,name=attest,proto3" json:"attest,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podr2_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_podr2_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetT() *Tag_T {
	if x != nil {
		return x.T
	}
	return nil
}

func (x *Tag) GetPhiHash() string {
	if x != nil {
		return x.PhiHash
	}
	return ""
}

func (x *Tag) GetAttest() string {
	if x != nil {
		return x.Attest
	}
	return ""
}

type RequestGenTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FragmentData     []byte        `protobuf:"bytes,1,opt,name=fragment_data,json=fragmentData,proto3" json:"fragment_data,omitempty"`
	FragmentName     string        `protobuf:"bytes,2,opt,name=fragment_name,json=fragmentName,proto3" json:"fragment_name,omitempty"`
	CustomData       string        `protobuf:"bytes,3,opt,name=custom_data,json=customData,proto3" json:"custom_data,omitempty"`
	FileName         string        `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MinerId          []byte        `protobuf:"bytes,5,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	TeeDigestList    []*DigestInfo `protobuf:"bytes,6,rep,name=tee_digest_list,json=teeDigestList,proto3" json:"tee_digest_list,omitempty"`
	LastTeeSignature []byte        `protobuf:"bytes,7,opt,name=last_tee_signature,json=lastTeeSignature,proto3" json:"last_tee_signature,omitempty"`
}

func (x *RequestGenTag) Reset() {
	*x = RequestGenTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podr2_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGenTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGenTag) ProtoMessage() {}

func (x *RequestGenTag) ProtoReflect() protoreflect.Message {
	mi := &file_podr2_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGenTag.ProtoReflect.Descriptor instead.
func (*RequestGenTag) Descriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{2}
}

func (x *RequestGenTag) GetFragmentData() []byte {
	if x != nil {
		return x.FragmentData
	}
	return nil
}

func (x *RequestGenTag) GetFragmentName() string {
	if x != nil {
		return x.FragmentName
	}
	return ""
}

func (x *RequestGenTag) GetCustomData() string {
	if x != nil {
		return x.CustomData
	}
	return ""
}

func (x *RequestGenTag) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *RequestGenTag) GetMinerId() []byte {
	if x != nil {
		return x.MinerId
	}
	return nil
}

func (x *RequestGenTag) GetTeeDigestList() []*DigestInfo {
	if x != nil {
		return x.TeeDigestList
	}
	return nil
}

func (x *RequestGenTag) GetLastTeeSignature() []byte {
	if x != nil {
		return x.LastTeeSignature
	}
	return nil
}

type DigestInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FragmentName []byte `protobuf:"bytes,1,opt,name=fragment_name,json=fragmentName,proto3" json:"fragment_name,omitempty"`
	TeeAccountId []byte `protobuf:"bytes,2,opt,name=tee_account_id,json=teeAccountId,proto3" json:"tee_account_id,omitempty"`
}

func (x *DigestInfo) Reset() {
	*x = DigestInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podr2_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DigestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestInfo) ProtoMessage() {}

func (x *DigestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_podr2_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestInfo.ProtoReflect.Descriptor instead.
func (*DigestInfo) Descriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{3}
}

func (x *DigestInfo) GetFragmentName() []byte {
	if x != nil {
		return x.FragmentName
	}
	return nil
}

func (x *DigestInfo) GetTeeAccountId() []byte {
	if x != nil {
		return x.TeeAccountId
	}
	return nil
}

type ResponseGenTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processing bool       `protobuf:"varint,1,opt,name=processing,proto3" json:"processing,omitempty"`
	Msg        *GenTagMsg `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseGenTag) Reset() {
	*x = ResponseGenTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podr2_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGenTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGenTag) ProtoMessage() {}

func (x *ResponseGenTag) ProtoReflect() protoreflect.Message {
	mi := &file_podr2_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGenTag.ProtoReflect.Descriptor instead.
func (*ResponseGenTag) Descriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseGenTag) GetProcessing() bool {
	if x != nil {
		return x.Processing
	}
	return false
}

func (x *ResponseGenTag) GetMsg() *GenTagMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

type GenTagMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag       *Tag   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	USig      []byte `protobuf:"bytes,2,opt,name=u_sig,json=uSig,proto3" json:"u_sig,omitempty"`
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *GenTagMsg) Reset() {
	*x = GenTagMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podr2_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenTagMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenTagMsg) ProtoMessage() {}

func (x *GenTagMsg) ProtoReflect() protoreflect.Message {
	mi := &file_podr2_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenTagMsg.ProtoReflect.Descriptor instead.
func (*GenTagMsg) Descriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{5}
}

func (x *GenTagMsg) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *GenTagMsg) GetUSig() []byte {
	if x != nil {
		return x.USig
	}
	return nil
}

func (x *GenTagMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RequestBatchVerify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggProof *RequestBatchVerify_BatchVerifyParam `protobuf:"bytes,1,opt,name=agg_proof,json=aggProof,proto3" json:"agg_proof,omitempty"`
	Qslices  *RequestBatchVerify_Qslice           `protobuf:"bytes,2,opt,name=qslices,proto3" json:"qslices,omitempty"`
	USigs    [][]byte                             `protobuf:"bytes,3,rep,name=u_sigs,json=uSigs,proto3" json:"u_sigs,omitempty"`
	MinerId  []byte                               `protobuf:"bytes,4,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
}

func (x *RequestBatchVerify) Reset() {
	*x = RequestBatchVerify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podr2_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBatchVerify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBatchVerify) ProtoMessage() {}

func (x *RequestBatchVerify) ProtoReflect() protoreflect.Message {
	mi := &file_podr2_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBatchVerify.ProtoReflect.Descriptor instead.
func (*RequestBatchVerify) Descriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{6}
}

func (x *RequestBatchVerify) GetAggProof() *RequestBatchVerify_BatchVerifyParam {
	if x != nil {
		return x.AggProof
	}
	return nil
}

func (x *RequestBatchVerify) GetQslices() *RequestBatchVerify_Qslice {
	if x != nil {
		return x.Qslices
	}
	return nil
}

func (x *RequestBatchVerify) GetUSigs() [][]byte {
	if x != nil {
		return x.USigs
	}
	return nil
}

func (x *RequestBatchVerify) GetMinerId() []byte {
	if x != nil {
		return x.MinerId
	}
	return nil
}

type ResponseBatchVerify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatchVerifyResult  bool     `protobuf:"varint,1,opt,name=batch_verify_result,json=batchVerifyResult,proto3" json:"batch_verify_result,omitempty"`
	TeeAccountId       []byte   `protobuf:"bytes,2,opt,name=tee_account_id,json=teeAccountId,proto3" json:"tee_account_id,omitempty"`
	ServiceBloomFilter []uint64 `protobuf:"varint,3,rep,packed,name=service_bloom_filter,json=serviceBloomFilter,proto3" json:"service_bloom_filter,omitempty"`
	Signature          []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *ResponseBatchVerify) Reset() {
	*x = ResponseBatchVerify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podr2_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseBatchVerify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBatchVerify) ProtoMessage() {}

func (x *ResponseBatchVerify) ProtoReflect() protoreflect.Message {
	mi := &file_podr2_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBatchVerify.ProtoReflect.Descriptor instead.
func (*ResponseBatchVerify) Descriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseBatchVerify) GetBatchVerifyResult() bool {
	if x != nil {
		return x.BatchVerifyResult
	}
	return false
}

func (x *ResponseBatchVerify) GetTeeAccountId() []byte {
	if x != nil {
		return x.TeeAccountId
	}
	return nil
}

func (x *ResponseBatchVerify) GetServiceBloomFilter() []uint64 {
	if x != nil {
		return x.ServiceBloomFilter
	}
	return nil
}

func (x *ResponseBatchVerify) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Tag_T struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	U    string   `protobuf:"bytes,2,opt,name=u,proto3" json:"u,omitempty"`
	Phi  []string `protobuf:"bytes,3,rep,name=phi,proto3" json:"phi,omitempty"`
}

func (x *Tag_T) Reset() {
	*x = Tag_T{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podr2_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag_T) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag_T) ProtoMessage() {}

func (x *Tag_T) ProtoReflect() protoreflect.Message {
	mi := &file_podr2_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag_T.ProtoReflect.Descriptor instead.
func (*Tag_T) Descriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Tag_T) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag_T) GetU() string {
	if x != nil {
		return x.U
	}
	return ""
}

func (x *Tag_T) GetPhi() []string {
	if x != nil {
		return x.Phi
	}
	return nil
}

type RequestBatchVerify_Qslice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RandomIndexList []uint32 `protobuf:"varint,1,rep,packed,name=random_index_list,json=randomIndexList,proto3" json:"random_index_list,omitempty"`
	RandomList      [][]byte `protobuf:"bytes,2,rep,name=random_list,json=randomList,proto3" json:"random_list,omitempty"`
}

func (x *RequestBatchVerify_Qslice) Reset() {
	*x = RequestBatchVerify_Qslice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podr2_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBatchVerify_Qslice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBatchVerify_Qslice) ProtoMessage() {}

func (x *RequestBatchVerify_Qslice) ProtoReflect() protoreflect.Message {
	mi := &file_podr2_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBatchVerify_Qslice.ProtoReflect.Descriptor instead.
func (*RequestBatchVerify_Qslice) Descriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{6, 0}
}

func (x *RequestBatchVerify_Qslice) GetRandomIndexList() []uint32 {
	if x != nil {
		return x.RandomIndexList
	}
	return nil
}

func (x *RequestBatchVerify_Qslice) GetRandomList() [][]byte {
	if x != nil {
		return x.RandomList
	}
	return nil
}

type RequestBatchVerify_BatchVerifyParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Us    []string `protobuf:"bytes,2,rep,name=us,proto3" json:"us,omitempty"`
	Mus   []string `protobuf:"bytes,3,rep,name=mus,proto3" json:"mus,omitempty"`
	Sigma string   `protobuf:"bytes,4,opt,name=sigma,proto3" json:"sigma,omitempty"`
}

func (x *RequestBatchVerify_BatchVerifyParam) Reset() {
	*x = RequestBatchVerify_BatchVerifyParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podr2_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBatchVerify_BatchVerifyParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBatchVerify_BatchVerifyParam) ProtoMessage() {}

func (x *RequestBatchVerify_BatchVerifyParam) ProtoReflect() protoreflect.Message {
	mi := &file_podr2_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBatchVerify_BatchVerifyParam.ProtoReflect.Descriptor instead.
func (*RequestBatchVerify_BatchVerifyParam) Descriptor() ([]byte, []int) {
	return file_podr2_api_proto_rawDescGZIP(), []int{6, 1}
}

func (x *RequestBatchVerify_BatchVerifyParam) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *RequestBatchVerify_BatchVerifyParam) GetUs() []string {
	if x != nil {
		return x.Us
	}
	return nil
}

func (x *RequestBatchVerify_BatchVerifyParam) GetMus() []string {
	if x != nil {
		return x.Mus
	}
	return nil
}

func (x *RequestBatchVerify_BatchVerifyParam) GetSigma() string {
	if x != nil {
		return x.Sigma
	}
	return ""
}

var File_podr2_api_proto protoreflect.FileDescriptor

var file_podr2_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x6f, 0x64, 0x72, 0x32, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x6f, 0x64, 0x72, 0x32, 0x22, 0x28, 0x0a, 0x0b, 0x45, 0x63, 0x68, 0x6f,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x63, 0x68, 0x6f, 0x5f,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x65, 0x63, 0x68, 0x6f, 0x4d,
	0x73, 0x67, 0x22, 0x8d, 0x01, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x1a, 0x0a, 0x01, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6f, 0x64, 0x72, 0x32, 0x2e, 0x54, 0x61,
	0x67, 0x2e, 0x54, 0x52, 0x01, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x68, 0x69, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x68, 0x69, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x0a, 0x01, 0x54, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x75,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x68, 0x69, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x70,
	0x68, 0x69, 0x22, 0x9b, 0x02, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65,
	0x6e, 0x54, 0x61, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x66, 0x72, 0x61,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x61,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x6d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0f, 0x74, 0x65, 0x65, 0x5f, 0x64,
	0x69, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x6f, 0x64, 0x72, 0x32, 0x2e, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x74, 0x65, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x65, 0x65, 0x5f, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10,
	0x6c, 0x61, 0x73, 0x74, 0x54, 0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x57, 0x0a, 0x0a, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23,
	0x0a, 0x0d, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x65, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x65, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x0e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x6e, 0x54, 0x61, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x6f, 0x64, 0x72, 0x32,
	0x2e, 0x47, 0x65, 0x6e, 0x54, 0x61, 0x67, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x5c, 0x0a, 0x09, 0x47, 0x65, 0x6e, 0x54, 0x61, 0x67, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x6f, 0x64, 0x72,
	0x32, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x13, 0x0a, 0x05, 0x75, 0x5f,
	0x73, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x53, 0x69, 0x67, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x84, 0x03,
	0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x12, 0x47, 0x0a, 0x09, 0x61, 0x67, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x6f, 0x64, 0x72, 0x32, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x52, 0x08, 0x61, 0x67, 0x67, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x3a, 0x0a,
	0x07, 0x71, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x70, 0x6f, 0x64, 0x72, 0x32, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x2e, 0x51, 0x73, 0x6c, 0x69, 0x63, 0x65,
	0x52, 0x07, 0x71, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x75, 0x5f, 0x73,
	0x69, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x75, 0x53, 0x69, 0x67, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x55, 0x0a, 0x06, 0x51,
	0x73, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x0f, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4c, 0x69,
	0x73, 0x74, 0x1a, 0x60, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x75, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x69, 0x67, 0x6d, 0x61, 0x22, 0xbb, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x2e, 0x0a, 0x13,
	0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x62, 0x61, 0x74, 0x63, 0x68,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0e,
	0x74, 0x65, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x65, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x62, 0x6c,
	0x6f, 0x6f, 0x6d, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x2a, 0xa1, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x16,
	0x0a, 0x11, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x10, 0x91, 0x4e, 0x12, 0x10, 0x0a, 0x0b, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x50, 0x61, 0x74, 0x68, 0x10, 0x92, 0x4e, 0x12, 0x12, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x93, 0x4e, 0x12, 0x10, 0x0a, 0x0b,
	0x4f, 0x75, 0x74, 0x4f, 0x66, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x10, 0x94, 0x4e, 0x12, 0x13,
	0x0a, 0x0e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x10, 0x95, 0x4e, 0x12, 0x11, 0x0a, 0x0c, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x10, 0x96, 0x4e, 0x32, 0x82, 0x01, 0x0a, 0x08, 0x50, 0x6f, 0x64, 0x72, 0x32,
	0x41, 0x70, 0x69, 0x12, 0x44, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x67,
	0x65, 0x6e, 0x5f, 0x74, 0x61, 0x67, 0x12, 0x14, 0x2e, 0x70, 0x6f, 0x64, 0x72, 0x32, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x54, 0x61, 0x67, 0x1a, 0x15, 0x2e, 0x70,
	0x6f, 0x64, 0x72, 0x32, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x6e,
	0x54, 0x61, 0x67, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x30, 0x0a, 0x04, 0x45, 0x63, 0x68,
	0x6f, 0x12, 0x12, 0x2e, 0x70, 0x6f, 0x64, 0x72, 0x32, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x2e, 0x70, 0x6f, 0x64, 0x72, 0x32, 0x2e, 0x45, 0x63,
	0x68, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x32, 0x63, 0x0a, 0x10, 0x50,
	0x6f, 0x64, 0x72, 0x32, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x41, 0x70, 0x69, 0x12,
	0x4f, 0x0a, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x19, 0x2e, 0x70, 0x6f, 0x64, 0x72, 0x32, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x1a, 0x1a, 0x2e, 0x70, 0x6f, 0x64, 0x72, 0x32, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x22, 0x00,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_podr2_api_proto_rawDescOnce sync.Once
	file_podr2_api_proto_rawDescData = file_podr2_api_proto_rawDesc
)

func file_podr2_api_proto_rawDescGZIP() []byte {
	file_podr2_api_proto_rawDescOnce.Do(func() {
		file_podr2_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_podr2_api_proto_rawDescData)
	})
	return file_podr2_api_proto_rawDescData
}

var file_podr2_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_podr2_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_podr2_api_proto_goTypes = []interface{}{
	(StatusCode)(0),                             // 0: podr2.StatusCode
	(*EchoMessage)(nil),                         // 1: podr2.EchoMessage
	(*Tag)(nil),                                 // 2: podr2.Tag
	(*RequestGenTag)(nil),                       // 3: podr2.RequestGenTag
	(*DigestInfo)(nil),                          // 4: podr2.DigestInfo
	(*ResponseGenTag)(nil),                      // 5: podr2.ResponseGenTag
	(*GenTagMsg)(nil),                           // 6: podr2.GenTagMsg
	(*RequestBatchVerify)(nil),                  // 7: podr2.RequestBatchVerify
	(*ResponseBatchVerify)(nil),                 // 8: podr2.ResponseBatchVerify
	(*Tag_T)(nil),                               // 9: podr2.Tag.T
	(*RequestBatchVerify_Qslice)(nil),           // 10: podr2.RequestBatchVerify.Qslice
	(*RequestBatchVerify_BatchVerifyParam)(nil), // 11: podr2.RequestBatchVerify.BatchVerifyParam
}
var file_podr2_api_proto_depIdxs = []int32{
	9,  // 0: podr2.Tag.t:type_name -> podr2.Tag.T
	4,  // 1: podr2.RequestGenTag.tee_digest_list:type_name -> podr2.DigestInfo
	6,  // 2: podr2.ResponseGenTag.msg:type_name -> podr2.GenTagMsg
	2,  // 3: podr2.GenTagMsg.tag:type_name -> podr2.Tag
	11, // 4: podr2.RequestBatchVerify.agg_proof:type_name -> podr2.RequestBatchVerify.BatchVerifyParam
	10, // 5: podr2.RequestBatchVerify.qslices:type_name -> podr2.RequestBatchVerify.Qslice
	3,  // 6: podr2.Podr2Api.request_gen_tag:input_type -> podr2.RequestGenTag
	1,  // 7: podr2.Podr2Api.Echo:input_type -> podr2.EchoMessage
	7,  // 8: podr2.Podr2VerifierApi.request_batch_verify:input_type -> podr2.RequestBatchVerify
	5,  // 9: podr2.Podr2Api.request_gen_tag:output_type -> podr2.ResponseGenTag
	1,  // 10: podr2.Podr2Api.Echo:output_type -> podr2.EchoMessage
	8,  // 11: podr2.Podr2VerifierApi.request_batch_verify:output_type -> podr2.ResponseBatchVerify
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_podr2_api_proto_init() }
func file_podr2_api_proto_init() {
	if File_podr2_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_podr2_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podr2_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podr2_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGenTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podr2_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DigestInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podr2_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGenTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podr2_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenTagMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podr2_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBatchVerify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podr2_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseBatchVerify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podr2_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag_T); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podr2_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBatchVerify_Qslice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podr2_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBatchVerify_BatchVerifyParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_podr2_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_podr2_api_proto_goTypes,
		DependencyIndexes: file_podr2_api_proto_depIdxs,
		EnumInfos:         file_podr2_api_proto_enumTypes,
		MessageInfos:      file_podr2_api_proto_msgTypes,
	}.Build()
	File_podr2_api_proto = out.File
	file_podr2_api_proto_rawDesc = nil
	file_podr2_api_proto_goTypes = nil
	file_podr2_api_proto_depIdxs = nil
}
