// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0-devel
// 	protoc        v5.26.1
// source: pubkey-api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The account id that the storage miner registered on the chain
	StorageMinerAccountId []byte `protobuf:"bytes,1,opt,name=storage_miner_account_id,json=storageMinerAccountId,proto3" json:"storage_miner_account_id,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pubkey_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pubkey_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pubkey_api_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetStorageMinerAccountId() []byte {
	if x != nil {
		return x.StorageMinerAccountId
	}
	return nil
}

type IdentityPubkeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the identity public key
	Pubkey []byte `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// The timestamp for the processing of the request
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Use the sr25519 algorithm to sign the timestamp fields above (use it's Big-Endian bytes)
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *IdentityPubkeyResponse) Reset() {
	*x = IdentityPubkeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pubkey_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityPubkeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityPubkeyResponse) ProtoMessage() {}

func (x *IdentityPubkeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pubkey_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityPubkeyResponse.ProtoReflect.Descriptor instead.
func (*IdentityPubkeyResponse) Descriptor() ([]byte, []int) {
	return file_pubkey_api_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityPubkeyResponse) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *IdentityPubkeyResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IdentityPubkeyResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type MasterPubkeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the master public key
	Pubkey []byte `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// The timestamp for the processing of the request
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Use the sr25519 algorithm to sign the timestamp fields above (use it's Big-Endian bytes)
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *MasterPubkeyResponse) Reset() {
	*x = MasterPubkeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pubkey_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterPubkeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterPubkeyResponse) ProtoMessage() {}

func (x *MasterPubkeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pubkey_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterPubkeyResponse.ProtoReflect.Descriptor instead.
func (*MasterPubkeyResponse) Descriptor() ([]byte, []int) {
	return file_pubkey_api_proto_rawDescGZIP(), []int{2}
}

func (x *MasterPubkeyResponse) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *MasterPubkeyResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MasterPubkeyResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Podr2PubkeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the PODR2 public key
	Pubkey []byte `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// The timestamp for the processing of the request
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Use the RSA algorithm to sign the timestamp fields above (use it's Big-Endian bytes)
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Podr2PubkeyResponse) Reset() {
	*x = Podr2PubkeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pubkey_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Podr2PubkeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Podr2PubkeyResponse) ProtoMessage() {}

func (x *Podr2PubkeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pubkey_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Podr2PubkeyResponse.ProtoReflect.Descriptor instead.
func (*Podr2PubkeyResponse) Descriptor() ([]byte, []int) {
	return file_pubkey_api_proto_rawDescGZIP(), []int{3}
}

func (x *Podr2PubkeyResponse) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *Podr2PubkeyResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Podr2PubkeyResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_pubkey_api_proto protoreflect.FileDescriptor

var file_pubkey_api_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x63, 0x65, 0x73, 0x65, 0x61, 0x6c, 0x2e, 0x70, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x73, 0x22, 0x42, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a,
	0x18, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x15, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x16, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x22, 0x6a, 0x0a, 0x14, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x75,
	0x62, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75,
	0x62, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x69, 0x0a, 0x13, 0x50, 0x6f, 0x64, 0x72, 0x32, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x32, 0x9b, 0x02, 0x0a, 0x15,
	0x43, 0x65, 0x73, 0x65, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x73, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x58, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x2e, 0x63,
	0x65, 0x73, 0x65, 0x61, 0x6c, 0x2e, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x65, 0x73, 0x65, 0x61, 0x6c, 0x2e, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x54, 0x0a, 0x11, 0x67, 0x65, 0x74, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x75,
	0x62, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x2e, 0x63, 0x65, 0x73, 0x65, 0x61, 0x6c, 0x2e, 0x70, 0x75,
	0x62, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x63, 0x65, 0x73, 0x65, 0x61, 0x6c, 0x2e, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x6f, 0x64,
	0x72, 0x32, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x2e, 0x63, 0x65, 0x73, 0x65,
	0x61, 0x6c, 0x2e, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x65, 0x73, 0x65, 0x61, 0x6c, 0x2e, 0x70, 0x75, 0x62, 0x6b,
	0x65, 0x79, 0x73, 0x2e, 0x50, 0x6f, 0x64, 0x72, 0x32, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pubkey_api_proto_rawDescOnce sync.Once
	file_pubkey_api_proto_rawDescData = file_pubkey_api_proto_rawDesc
)

func file_pubkey_api_proto_rawDescGZIP() []byte {
	file_pubkey_api_proto_rawDescOnce.Do(func() {
		file_pubkey_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pubkey_api_proto_rawDescData)
	})
	return file_pubkey_api_proto_rawDescData
}

var file_pubkey_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pubkey_api_proto_goTypes = []interface{}{
	(*Request)(nil),                // 0: ceseal.pubkeys.Request
	(*IdentityPubkeyResponse)(nil), // 1: ceseal.pubkeys.IdentityPubkeyResponse
	(*MasterPubkeyResponse)(nil),   // 2: ceseal.pubkeys.MasterPubkeyResponse
	(*Podr2PubkeyResponse)(nil),    // 3: ceseal.pubkeys.Podr2PubkeyResponse
}
var file_pubkey_api_proto_depIdxs = []int32{
	0, // 0: ceseal.pubkeys.CesealPubkeysProvider.get_identity_pubkey:input_type -> ceseal.pubkeys.Request
	0, // 1: ceseal.pubkeys.CesealPubkeysProvider.get_master_pubkey:input_type -> ceseal.pubkeys.Request
	0, // 2: ceseal.pubkeys.CesealPubkeysProvider.get_podr2_pubkey:input_type -> ceseal.pubkeys.Request
	1, // 3: ceseal.pubkeys.CesealPubkeysProvider.get_identity_pubkey:output_type -> ceseal.pubkeys.IdentityPubkeyResponse
	2, // 4: ceseal.pubkeys.CesealPubkeysProvider.get_master_pubkey:output_type -> ceseal.pubkeys.MasterPubkeyResponse
	3, // 5: ceseal.pubkeys.CesealPubkeysProvider.get_podr2_pubkey:output_type -> ceseal.pubkeys.Podr2PubkeyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pubkey_api_proto_init() }
func file_pubkey_api_proto_init() {
	if File_pubkey_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pubkey_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pubkey_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityPubkeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pubkey_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterPubkeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pubkey_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Podr2PubkeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pubkey_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pubkey_api_proto_goTypes,
		DependencyIndexes: file_pubkey_api_proto_depIdxs,
		MessageInfos:      file_pubkey_api_proto_msgTypes,
	}.Build()
	File_pubkey_api_proto = out.File
	file_pubkey_api_proto_rawDesc = nil
	file_pubkey_api_proto_goTypes = nil
	file_pubkey_api_proto_depIdxs = nil
}
